### PR TITLE
Allow async PostCSS plugins

### LINKED ISSUE #2: Doesn't support async postcss plugins
`Error: Use process(css).then(cb) to work with async plugins`

### PR DESCRIPTION
**Pull request by devinus**
Closes #2.

@voischev

### CODE REVIEW

**Comment by awinogradov** [comment]
:+1:

**Comment by voischev** [comment]
@devinus thx!

**Comment by devinus** [comment]
@voischev Was there anything you saw unfavorable with how I did it? I'm doing this pattern elsewhere too.

**Comment by voischev** [comment]
@devinus Everything looks good ;)

**Pull request merged**
